import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Poppins } from "next/font/google";




 // Assuming "Poppins" is available as a font
import "./globals.css";
import Navbar from "@/components/Navbar";


const poppins = Poppins({ subsets: ["latin"], weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "EduGenius",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={cn(poppins.className, "antialiased min-h-screen pt-16")}>
      <Navbar/>

        {children}</body>
    </html>
  );
}
