import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarNew from "@/components/NavbarNew";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import {Toaster} from "react-hot-toast"
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "EduGenius",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const session= await auth();
  return (
    <html lang="en">
      <body className={cn(poppins.className, "antialiased min-h-screen")}>
      <SessionProvider session={session}>
      <Toaster/>
      <div className="">
      <NavbarNew/>
      {children}
      </div>  
      </SessionProvider>
      </body>
    </html>
  );
}
